# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    crv.doctrine_entity_repository.task:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Task
    crv.doctrine_entity_repository.pause:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Pause
    app.jwt_token_authenticator:
            parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
            class: AppBundle\Security\Guard\JWTAuthenticator

